apiVersion: v1
kind: Service
metadata:
  name: istiodemo-service
  labels:
    app: istiodemo-service
spec:
  type: NodePort
  ports:
  - port: 8080
    name: http
  selector:
    app: istiodemo-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: istiodemo-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: istiodemo-service
      version: v1
  template:
    metadata:
      labels:
        app: istiodemo-service
        version: v1
    spec:
      containers:
      - name: istiodemo-service
        image: eu.gcr.io/wave31-webhelp-rubendarion/istiodemo:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
---
apiVersion: networking.istio.io/v1alpha3  
kind: Gateway  
metadata:  
  name: istiodemo-gateway  
spec:  
  selector:  
    istio: ingressgateway # use Istio default gateway implementation  
  servers:  
  - port:  
      name: http  
      number: 80  
      protocol: HTTP  
    hosts:  
    - '*'  
---  
apiVersion: networking.istio.io/v1alpha3  
kind: VirtualService  
metadata:  
  name: istiodemo-service  
spec:  
  hosts:  
  - "*"  
  gateways:  
  - istiodemo-gateway  
  http:  
  - match:  
    - uri:  
        prefix: /  
    route:  
    - destination:  
        port:  
          number: 8080  
        host: istiodemo-service
        subset: v1
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: istiodemo-service
spec:
  host: istiodemo-service
  subsets:
    - name: v1
      labels:
        version: "v1"
