apiVersion: v1
kind: Service
metadata:
  name: istiodemo-service
  labels:
    app: istiodemo-service
spec:
  type: NodePort
  ports:
  - port: 8080
    name: http
  selector:
    app: istiodemo-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: istiodemo-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: istiodemo-service
      version: v1  
  template:
    metadata:
      labels:
        app: istiodemo-service
        version: v1
    spec:
      containers:
      - name: istiodemo-service
        image: eu.gcr.io/wave31-webhelp-rubendarion/istiodemo:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: istiodemo-service-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: istiodemo-service
      version: v2  
  template:
    metadata:
      labels:
        app: istiodemo-service
        version: v2
    spec:
      containers:
      - name: istiodemo-service
        image: eu.gcr.io/wave31-webhelp-rubendarion/istiodemo:2.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080          
---          
apiVersion: apps/v1
kind: Deployment
metadata:
  name: istiodemo-service-v3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: istiodemo-service
      version: v4  
  template:
    metadata:
      labels:
        app: istiodemo-service
        version: v4
    spec:
      containers:
      - name: istiodemo-service
        image: eu.gcr.io/wave31-webhelp-rubendarion/istiodemo:3.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080          
---          
apiVersion: apps/v1
kind: Deployment
metadata:
  name: istiodemo-service-v4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: istiodemo-service
      version: v4  
  template:
    metadata:
      labels:
        app: istiodemo-service
        version: v4
    spec:
      containers:
      - name: istiodemo-service
        image: eu.gcr.io/wave31-webhelp-rubendarion/istiodemo:4.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
---          
apiVersion: networking.istio.io/v1alpha3  
kind: Gateway  
metadata:  
  name: istiodemo-gateway  
spec:  
  selector:  
    istio: ingressgateway # use Istio default gateway implementation  
  servers:  
  - port:  
      name: http  
      number: 80  
      protocol: HTTP  
    hosts:  
    - '*'  
---  
apiVersion: networking.istio.io/v1alpha3  
kind: VirtualService  
metadata:  
  name: istiodemo-service  
spec:  
  hosts:  
  - "*"  
  gateways:  
  - istiodemo-gateway  
  http:  
  - fault:
      delay:
        percentage:
          value: 1
        fixedDelay: 10s  
      abort:
        httpStatus: 500
        percentage:
          value: 10
    match:  
    - uri:  
        prefix: /  
    route:  
    - destination:  
        port:  
          number: 8080  
        host: istiodemo-service
        subset: v1
      weight: 50
    - destination:  
        port:  
          number: 8080  
        host: istiodemo-service
        subset: v2
      weight: 30
    - destination:
        port:
          number: 8080
        host: istiodemo-service
        subset: v3
      weight: 10
    - destination:
        port:
          number: 8080
        host: istiodemo-service
        subset: v4
      weight: 100
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: istiodemo-service
spec:
  host: istiodemo-service
  subsets:
    - name: v1
      labels:
        version: "v1"
    - name: v2
      labels:
        version: "v2"
    - name: v3
      labels:
        version: "v3"
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: deny-path-api
  namespace: default
spec:
  selector:
    matchLabels:
      app: istiodemo-service
  action: DENY
  rules:
  - to:
    - operation:
        paths: ["/secre"]
